# Generated by Django 6.0.1 on 2026-01-19 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.CharField(max_length=100),
        ),
    ]
